name: customerchurn_classification_app
description: Customer Churn Classification App
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.0.0
  flutter_native_splash: ^2.2.19
  form_builder_validators: ^9.0.0
  freezed: ^2.3.2
  get: ^4.6.5
  intl: ^0.18.0
  sizer: ^2.0.15

dev_dependencies:
  build_runner: any
  flutter_gen_runner: null
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/resources/images/launcher_icon.png"
  adaptive_icon_foreground: "lib/resources/images/ic_launcher_adaptive_fore.png"
  adaptive_icon_background: "lib/resources/images/ic_launcher_adaptive_back.png"

flutter_gen:
  output: lib/resources/

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Light.ttf
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Medium.ttf
        - asset: assets/fonts/DMSans-SemiBold.ttf